Repository 10teamProject/Thejulge, pull requests merged in 2024-07, with the labels that each got.

#76 [#71] 공고신청 수락 및 거절
  public/assets/icon/check_Icon.svg
  src/components/common/ConfirmModal.module.scss
  src/components/common/ConfirmModal.tsx
  src/components/myStore/ApplicantList.module.scss
  src/components/myStore/ApplicantList.tsx
  src/components/myStore/ApplicantRow.tsx
  src/components/myStore/MyNotice.module.scss
  src/components/myStore/MyNotice.tsx
  src/components/myStore/MyNoticeDetail.module.scss
  src/components/myStore/MyNoticeDetial.tsx
  src/components/myStore/MyStore.module.scss
  src/components/myStore/MyStore.tsx
  src/components/myStore/NoNotice.module.scss
  src/components/myStore/NoNotice.tsx
  src/hooks/useApplicants.tsx
  src/pages/api/ApplicationStatus.ts
  src/pages/api/ManageNotice.ts
  src/pages/mystore/[id]/index.tsx
  src/pages/mystore/[id]/notice/[notice_id].tsx
Labels: 🍀feat

#78 [#70] 푸터 제작 및 가게 정보 반응형
  public/assets/icon/icon_facebook.svg
  public/assets/icon/icon_instagram.svg
  public/assets/icon/icon_mail.svg
  src/components/auth/ErrorModal.tsx
  src/components/common/Button.module.scss
  src/components/common/Button.tsx
  src/components/common/Footer.module.scss
  src/components/common/Footer.tsx
  src/components/common/Header.module.scss
  src/components/common/InputComponent.tsx
  src/components/dropDown/DropDown.module.scss
  src/components/storeRegister/ImageUpload.module.scss
  src/hooks/useWindowSize.ts
  src/pages/_app.tsx
  src/pages/api/RegisterStore.ts
  src/pages/storeRegister/StoreRegister.module.scss
  src/pages/storeRegister/index.tsx
  src/styles/globals.css
Labels: 🍀feat

#83 [#82] 가게 등록 후 /mystore 리다이렉트 구현
  .env
  src/pages/mystore/Mystore.module.scss
  src/pages/mystore/index.tsx
Labels: 💭refact, 🛠️fix

#84 [#77] 내 가게 공고 등록
  src/components/addNotice/AddNotice.module.scss
  src/components/addNotice/AddNotice.tsx
  src/components/auth/ErrorModal.module.scss
  src/components/common/HeaderComponent.tsx
  src/components/myStore/MyNotice.module.scss
  src/components/myStore/MyNotice.tsx
  src/components/myStore/MyStore.tsx
  src/components/myStore/NoNotice.tsx
  src/form/signup/SignUpForm.tsx
  src/pages/api/AddNotice.tsx
  src/pages/mystore/[id]/addNotice/index.tsx
Labels: 💭refact, 🍀feat

#88 [#87] 검색 기능
  src/components/common/HeaderComponent.tsx
  src/components/listPage/FitNotice.module.scss
  src/components/listPage/FitNotice.tsx
  src/components/listPage/Search.module.scss
  src/components/listPage/Search.tsx
  src/pages/listPage/ListPage.module.scss
  src/pages/listPage/index.tsx
Labels: 🍀feat

#90 [#79] 가게 정보 편집 기능 추가
  public/assets/icon/icon_camera_white.svg
  src/components/myStore/MyStore.tsx
  src/components/storeRegister/ImageUpload.tsx
  src/pages/api/UpdateStore.ts
  src/pages/storeRegister/StoreRegister.module.scss
  src/pages/storeRegister/index.tsx
  src/styles/globals.css
Labels: 🍀feat

#91 [#81] 상세페이지 토스트 메시지 구현하기
  src/components/common/ToastMessage.module.scss
  src/components/common/ToastMessage.tsx
  src/pages/detailPage/index.tsx
Labels: 🍀feat

#93 [#85] 헤더 알림창 제작
  public/assets/icon/nofication-active.svg
  public/assets/icon/notification.svg
  src/components/addNotice/AddNotice.tsx
  src/components/common/Header.module.scss
  src/components/common/HeaderComponent.tsx
  src/components/myStore/MyNotice.tsx
  src/components/userNofication/UserNofication.module.scss
  src/components/userNofication/UserNofication.tsx
  src/hooks/useOutsideClick.ts
  src/pages/api/AddNotice.ts
  src/pages/api/GetMyAlert.ts
  src/pages/detailPage/index.tsx
  src/pages/mystore/[id]/index.tsx
  src/types/notificationType.ts
  src/utils/DateUtile.ts
Labels: 🍀feat

#98 [#94] 페이지 연결, 맞춤 공고 슬라이드
  package.json
  src/components/listPage/FilterDropdown.module.scss
  src/components/listPage/FilterDropdown.tsx
  src/components/listPage/FitNotice.module.scss
  src/components/listPage/FitNotice.tsx
  src/components/listPage/NoticeCard.module.scss
  src/components/listPage/NoticeCard.tsx
  src/pages/listPage/ListPage.module.scss
  yarn.lock
Labels: 🍀feat

#99 [Feat/#92] 상세페이지 폴더 구조 변경과 컴포넌트 분리완료, 카드 클릭 시 페이지 이동, 카드 이미지 적용완료
  src/components/detailPage/Card.module.scss
  src/components/detailPage/Card.tsx
  src/components/detailPage/StoreNotice.module.scss
  src/components/detailPage/StoreNotice.tsx
  src/pages/detailPage/[shop_id]/[notice_id]/DetailPage.module.scss
  src/pages/detailPage/[shop_id]/[notice_id]/index.tsx
  src/pages/detailPage/index.tsx
  src/types/detailPageType.ts
Labels: 💭refact, 🍀feat

#101 [#95] 404 페이지 추가
  src/components/common/Button.module.scss
  src/components/common/Container.tsx
  src/components/myStore/MyStore.tsx
  src/pages/404/404.module.scss
  src/pages/404/index.tsx
  src/pages/_app.tsx
  src/styles/globals.css
Labels: 🍀feat

#102 [#102] UI 디자인 및 put 요청 받아와서 UI 렌더링, 데이터가있을경우 UI 렌더링 변경
  .env
  public/assets/images/location.svg
  src/components/detail_Profile/DetailCard.module.scss
  src/components/detail_Profile/Detailcard.tsx
  src/components/detail_Profile/RenderingMyPage.module.scss
  src/components/detail_Profile/RenderingMyPage.tsx
  src/pages/DetailedMyPage/MyPage.module.scss
  src/pages/DetailedMyPage/index.tsx
  src/pages/PostMyPage/index.tsx
Labels: 🍀feat

#103 [#96] 반응형 제작
  src/components/addNotice/AddNotice.module.scss
  src/components/common/Header.module.scss
  src/components/common/HeaderComponent.tsx
  src/components/listPage/Search.module.scss
  src/components/myStore/ApplicantList.module.scss
  src/components/myStore/ApplicantRow.tsx
  src/components/myStore/MyNotice.module.scss
  src/components/myStore/MyNoticeDetail.module.scss
  src/components/myStore/MyStore.module.scss
  src/components/myStore/MyStore.tsx
  src/components/myStore/NoNotice.module.scss
  src/hooks/useApplicants.tsx
Labels: 🍀feat

#107 [#106] 내 프로필 정보 편집하기
  public/assets/icon/phone.svg
  public/assets/images/loacation.svg
  public/assets/images/phone.svg
  src/components/detailPage/StoreNotice.tsx
  src/components/detail_Profile/RenderingMyPage.module.scss
  src/components/detail_Profile/RenderingMyPage.tsx
  src/pages/DetailedMyPage/MyPage.module.scss
  src/pages/PostMyPage/index.tsx
Labels: 🍀feat, 🛠️fix

#110 [#105] 리스트 페이지
  src/components/listPage/FilterDropdown.module.scss
  src/components/listPage/FilterDropdown.tsx
  src/components/listPage/NoticeCard.module.scss
  src/components/listPage/NoticeCard.tsx
  src/pages/listPage/ListPage.module.scss
  src/pages/listPage/index.tsx
Labels: 🍀feat

#115 [#109] 가게 등록 다음 주소 검색 추가
  eslint.config.js
  src/components/auth/Input.module.scss
  src/components/common/InputComponent.tsx
  src/components/common/InputComponents.tsx
  src/components/storeRegister/DaumAddressInput.module.scss
  src/components/storeRegister/DaumAddressInput.tsx
  src/pages/_document.tsx
  src/pages/storeRegister/StoreRegister.module.scss
  src/pages/storeRegister/index.tsx
  src/utils/GetNumberOnly.ts
  src/utils/validation/Message.ts
Labels: 💭refact, 🍀feat

#116 [#114] 상세페이지 버튼 버그 수정
  src/components/detailPage/Card.tsx
  src/components/detailPage/StoreNotice.module.scss
  src/components/detailPage/StoreNotice.tsx
  src/pages/detailPage/[shop_id]/[notice_id]/index.tsx
  src/types/detailPageType.ts
Labels: 🛠️fix

#118 [#117] list page
  src/pages/listPage/ListPage.module.scss
  src/pages/listPage/index.tsx
Labels: 💭refact

#119 [#112] 일부 리팩토링
  public/assets/font/BagelFatOne-Regular.ttf
  public/assets/images/coinicons.png
  public/favicon.ico
  src/components/addNotice/AddNotice.tsx
  src/components/common/Header.module.scss
  src/components/common/HeaderComponent.tsx
  src/components/common/LoadingSpinner.module.scss
  src/components/common/Spinner.tsx
  src/components/detailPage/Card.tsx
  src/components/detailPage/StoreNotice.tsx
  src/components/myStore/ApplicantList.module.scss
  src/components/myStore/ApplicantList.tsx
  src/components/myStore/MyNotice.module.scss
  src/components/myStore/MyNotice.tsx
  src/components/myStore/MyNoticeDetial.tsx
  src/hooks/useApplicants.tsx
  src/pages/DetailedMyPage/index.tsx
  src/pages/_document.tsx
  src/pages/detailPage/[shop_id]/[notice_id]/index.tsx
  src/pages/login/LoginPage.module.scss
  src/pages/login/index.tsx
  src/pages/signup/SignUpPage.module.scss
  src/pages/signup/index.tsx
Labels: 💭refact

#121 [#112] 로딩스피너 처리
  src/components/common/LoadingSpinner.module.scss
  src/components/listPage/NoticeCard.tsx
  src/components/myStore/MyNotice.module.scss
  src/components/myStore/MyNotice.tsx
  src/components/myStore/MyStore.module.scss
Labels: 💭refact

#122 [#120] 내 가게 등록 리팩토링
  src/pages/mystore/index.tsx
  src/pages/storeRegister/index.tsx
  src/utils/storeRegister/formUtils.ts
  src/utils/validation/Message.ts
Labels: 💭refact

#123 [#108] 내 프로필 신청 내역
  package.json
  public/assets/icon/apply.svg
  public/assets/icon/pending.svg
  public/assets/icon/phone.svg
  public/assets/icon/rejection.svg
  src/components/common/PageNation.module.scss
  src/components/detailProfile/ApplicantList.module.scss
  src/components/detailProfile/ApplicantRow.tsx
  src/components/detailProfile/ApplicantTable.module.scss
  src/components/detailProfile/ApplicantTable.tsx
  src/components/detailProfile/DetailCard.module.scss
  src/components/detailProfile/Detailcard.tsx
  src/components/detailProfile/RenderingMyPage.module.scss
  src/components/detailProfile/RenderingMyPage.tsx
  src/components/detail_Profile/RenderingMyPage.module.scss
  src/pages/DetailedMyPage/MyPage.module.scss
  src/pages/DetailedMyPage/index.tsx
  src/pages/PostMyPage/PostMyPage.module.scss
  src/pages/api/AxiosInstance.ts
  src/pages/api/GetUserNotice.tsx
  yarn.lock
Labels: 🍀feat

#126 fix : 가게 등록 컴포넌트에서 주소 변경 핸들러 리팩토링
  src/pages/storeRegister/index.tsx
Labels: 🛠️fix

#127 [#125] 테이블 리팩토링
  src/components/auth/ErrorModal.module.scss
  src/components/detailProfile/ApplicantTable.module.scss
  src/components/detailProfile/ApplicantTable.tsx
  src/components/detailProfile/RenderingMyPage.module.scss
  src/components/detailProfile/RenderingMyPage.tsx
  src/components/userNofication/UserNofication.module.scss
  src/components/userNofication/UserNofication.tsx
Labels: 💭refact
